### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by ThomSwiss** [barnstee/SwissQRCodeExcel#2]
Hello Erich

Thank you for sharing this code.
Please can you describe in a few words, what I have to do to use your excel? I played arround a little bit and was not able to use it.

Regards
Thomas

**Comment by barnstee** [comment]
Thanks @ThomSwiss. I've updated the main page with an installation and usage section.

**Comment by ThomSwiss** [comment]
Thanks a log. Regards
Thomas

**Comment by ThomSwiss** [comment]
It works. I was able to us it.

**Comment by TheFlyingBox** [comment]
Hi,
I'm unable to install, I get this error after loading the project in Visual Studio when I try to publish :
`Unable to get MD5 checksum for the key file "SwissQRCode_1_TemporaryKey.pfx". Could not find file 'C:\Users\Me\Source\Repos\SwissQRCodeExcel\SwissQRCode_1_TemporaryKey.pfx'.`

Could you tell me how I can fix this ?

**Comment by ThomSwiss** [comment]
It works. I was able to us it.
