### ISSUE TITLE
Office 365

### ISSUE THREAD

**Issue by Nilanka031** [barnstee/SwissQRCodeExcel#4]
Hi,

Could you let me know whether this SwissQR Code is working on Office 365?

**Comment by barnstee** [comment]
Yes.

**Comment by Nilanka031** [comment]
Hi Barnstee, 

On office 365 the Qr button doesnt appear on the ribbon. I read the VSTO file doesnt support on the office 365. Do you have a workaround for that? Thanks in advance for your support.

**Comment by barnstee** [comment]
Do you mean the web version of Excel? That is indeed not supported. The version of Excel (which is part of the O365 suite) that you can install on our PC is supported.

**Comment by Nilanka031** [comment]
Thanks for the response. What we do is we have a sharepoint and the files
are in it and we use a virtual desktop from Azure and run the work from
there.

The O365 suite is installed on the virtual machine.

**Comment by barnstee** [comment]
Then it should work. I did have some problems installing the plugin when I was not admin on the machine.

**Comment by Nilanka031** [comment]
I did check with a colleagues local machine O365 but the ribbon didn't
install.

When I read few articles it was showing me that O365 doesn't support COM
and VSTO is that true.

is there anyway we could publish it in a different format that supports
O365?

Thanks for all the quick responses

**Comment by barnstee** [comment]
Not to my knowledge, no. O365 is using "normal" Excel.

**Comment by Nilanka031** [comment]
ok thanks for the response. let me try a bit more

**Comment by Nilanka031** [comment]
Hi Erich,

I have tried all the solutions but cant get the QR button on the ribbon.

The addin shows in O365 as inactive but though I activate it, doesnt come
to the ribbon. Do you know any solutions.

Thanks for your usual help.

Best regards
Nilanka

**Comment by barnstee** [comment]
Well, at least the add-on shows up! :-) I bet you anything it is a permission issue. Do you have admin permissions or can ask someone with admin permissions to install it?

**Comment by Nilanka031** [comment]
we tried it on a local machine with O365 which is with admin rights but its
the same.

Shows up on the inactive list only and doesn't get activated

**Comment by barnstee** [comment]
I had problems when the built version doesn't match the target architecture of Office: Is it the x86 or x64 version of office?

**Comment by Nilanka031** [comment]
Hi Eric

It is the x64 version. I couldn't get the ribbon activated so trying with
Phyton if it is possible to run the QR code.

**Comment by Nilanka031** [comment]
if you manage to get it running please let me know.

**Comment by barnstee** [comment]
Ah, ok. I extended the plugin to also work with SEPA transfers today and noticed that the debug version was set to x86. It is now set to "Any CPU". Perhaps sync and build the installer again today?

**Comment by Nilanka031** [comment]
oh thank you so much for the update will try it tomorrow morning. and keep
you posted.
